---
title: "SIBEC Regressions"
author: "Will MacKenzie/Kiri Daust"
date: "17/06/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, warning = FALSE)
require(dplyr)
require(ggplot2)
require(magrittr)
require(foreach)
require(reshape2)
require(reticulate)
require(Rcpp)
library(data.table)
library(scales)
require(rgdal)
require(tidyverse)
require(randomForest)
require(Rcpp)
require(openxlsx)

calcCMD <- function(CMD, rSMR){
  diff <- rSMR - 4
  if(diff > 0){
    return(CMD/2^diff)
  }else if(diff < 0){
    return(CMD + 100*abs(diff))
  }else{
    return(CMD)
  }
}
calcCMD_vec <- Vectorize(calcCMD)

cppFunction('NumericVector calcASMR(NumericVector rSMR,NumericVector CMD, DataFrame Rules) {
  NumericVector rSMRLev = Rules["SMRLevel"];
  NumericVector CMDctf = Rules["CMD"];
  NumericVector aSMR = Rules["aSMR"];
  int len = CMD.length();
  IntegerVector v;
  NumericVector out(len);
  for(int i = 0; i < len; i++){
    v = Rcpp::seq(0, aSMR.length()-1);
    if(rSMR[i] < 5){
      v = v[rSMRLev == 0];
    }else if(rSMR[i] == 5){
      v = v[rSMRLev == 5];
    }else if(rSMR[i] == 6){
      v = v[rSMRLev == 6];
    }else{
      v = v[rSMRLev == 7];
    }
    int j;
    for(j = v[0]; j < v[v.length()-1]; j++){
      if(CMD[i] <= CMDctf[j]){
        break;
      }
    }
    out[i] = aSMR[j];
  }
  return(out);
}')

addVars <- function(dat){
  dat[,`:=`(PPT_MJ = PPT05+PPT06,
            PPT_JAS = PPT07+PPT08+PPT09,
            PPT.dormant = PPT_at+PPT_wt)]
  dat[,`:=`(CMD.def = 500-PPT.dormant)]
  dat[CMD.def < 0, CMD.def := 0]
  dat[,`:=`(CMDMax = CMD07,
            CMD.total = CMD.def +CMD,
            CMD.grow = CMD05 + CMD06 +CMD07 +CMD08 +CMD09,
            DD5.grow = DD5_05 + DD5_06 + DD5_07 + DD5_08 + DD5_09,
            DDgood = DD5 - DD18,
            DDnew = (DD5_05 + DD5_06 +DD5_07  + DD5_08)  - 
              (DD18_05 + DD18_06 +DD18_07 +DD18_08),
            TmaxJuly = Tmax07)]

# remove some redundant variables considered undesireable
  nms <- as.character(names(dat))
  toRemove <- c("01", "02", "03", "04", "05", "06","07", "08", "09", "10", "11", "12","Rad","RH")
  nms <- nms[grep(paste(toRemove,collapse = "|"),nms)]
  dat[,(nms) := NULL]
  dat <- dat[CMD != -9999]

  return(dat)
}


```

```{r importData}
#sibec <- sibec %>% distinct()
#write.csv(sibec, "./inputsGit/SIBEC_2020_updatesof2013.csv", row.names = FALSE)
##Set drive with cloud data
if(dir.exists("C:/users/whmacken/Sync")){
  cloud_dir <- "C:/users/whmacken/Sync/CCISS_data/CommonTables/"
}else{
  cloud_dir <- "C:/Users/kirid/Sync/CCISS_data/CommonTables/"
}

sibec0 <- fread("./inputsGit/SIBEC_2020_updatesof2013.csv")
sibec_add <- fread("./inputsGit/SIBEC_2020_Add.csv") ## additional SI Max values added
sibec_add <- sibec_add %>% dplyr::select(-Source)
sibec0 <- rbind(sibec0, sibec_add)
sibec0 <- sibec0[!is.na(MeanPlotSiteIndex),]
MaxSppSI <-  fread("./inputsGit/MaxSppSI.csv") ## file with highest know SI values by species

##load and average climate data
climDat0 <- fread(paste0(cloud_dir,"WNA_4k_HexPts_BGC_Normal_1961_1990MSY.csv"))
climDat0 <- addVars(climDat0)
climDat <- climDat0[,lapply(.SD, mean), by = .(BGC), .SDcols = 6:86] 

climDat2 <-climDat %>% dplyr::select(BGC, CMD.total)

eda <- fread(paste0(cloud_dir,"Edatopic_v11_20.csv"))
#eda <- eda[is.na(Special),.(BGC,SS_NoSpace,Edatopic)]
eda[,`:=`(rSMR = as.numeric(substr(Edatopic,2,2)),SNR = substr(Edatopic,1,1))]
eda <- unique(eda)

rules <- fread("./inputsGit/aSMR_Rules_HalfStep_v11_09Dec2019.csv")
```

```{r clean data}
SppCurr = "Ba"
sibec <- sibec0
sppAdj <- data.table(read.xlsx("./inputsGit/SI_percent_by_edagrid.xlsx",sheet = SppCurr))
sppAdj$aSMR <- 0:9
sppAdj <- data.table::melt(sppAdj, id.vars = "aSMR", variable.name = "SNR")

SppMaxSI <- MaxSppSI[MaxSppSI$Sp %in% SppCurr,]
sibec <- sibec[TreeSpp == SppCurr,]
sibec[,BGC := gsub("/.*","",SS_NoSpace)]

sibec[,isMax := MeanPlotSiteIndex == max(MeanPlotSiteIndex), by = .(BGC)]
simax <- sibec[(isMax),] 
simax <- simax %>% dplyr::rename (XSI = MeanPlotSiteIndex) %>% unique()

##check if max SI values are near max climatic potential (final table is simaxAvg)
simax2 <- eda[simax, on = "SS_NoSpace"]
simax2 <- climDat[,.(BGC,CMD.total)][simax2, on = "BGC"]
simax2 <- simax2[!is.na(CMD.total),]
simax2[, CMDadj := calcCMD_vec(CMD.total,rSMR)]
simax2[, aSMR := calcASMR(rSMR,CMDadj,rules)]
simax2[, aSMR := round(aSMR, digits = 0)]

simax2 <- sppAdj[simax2, on = c("aSMR","SNR")]
simaxAvg <- simax2[,.(BGC,XSI,PropMax = mean(as.numeric(value))), by = .(SS_NoSpace)]
simaxAvg <- unique(simaxAvg)

toRemove <- simaxAvg[PropMax < 0.6, SS_NoSpace]
simax <- simax[!SS_NoSpace %in% toRemove,]
# simax <- simaxAvg[,.(SS_NoSpace,PropMax)] [simax, on = "SS_NoSpace"]
# simax[!is.na(PropMax),XSI := XSI*(1/PropMax)]

###----will need to remove or adjust the SI where the max is on suboptimal CMD sites (e.g. where species only occurs on warm, dry sites)

##-------Removed values of BGCs with issues
if(SppCurr == "Fd"){
simax <- simax %>%  filter(!str_detect(simax$BGC, ("CDFmm|SBPSxc|IDFxm|ESSFmw|IDFdk4|ESSFxw_OR|IDFxh2|IDFdm2|IDFdm1|IDFxw|IDFxh1|IDFdk|SBSmw|SBSdw|ICHmk")))
}#,
if(SppCurr == "Pl"){
simax <- simax %>%  filter(!str_detect(simax$BGC, ("BWBS|IDFmw|IDFxm|ESSFxw|IDFdk")))
}

if(SppCurr == "Sx"){
simax <- simax %>%  filter(!str_detect(simax$BGC, ("BWBS|IDFdw|IDFdk|SBPS|ESSFdc")))
}
##-------Removed for Bg curves
#simax <- simax %>% filter(!str_detect(simax$BGC, ("CDFmm|SBPSxc|IDFxm|ESSFmw|IDFdk4|ESSFxw_OR|IDFxh2|IDFdm2|IDFdm1|IDFxw|IDFxh1|IDFdk|SBSmw|SBSdw|ICHmk")))

climSI <- left_join(simax, climDat) %>% dplyr::select(BGC, XSI, DD5, DD18, EXT) #%>% mutate(XSIadj = ifelse (DD5 >= 1100, XSI + ((DD5 - 1100) *.02), XSI))

coast <- "CWH|CDF|CMX|MH|MHRF|CVG|CRF|CMA|CWF|CCH|IDFww|ESSFmk|IWF|OW|ESSFmw"
coastSI <- climSI %>% dplyr::filter(str_detect(BGC, (coast))) #%>% 
#  dplyr::filter(!XSI == 28, !XSI == 21,!XSI == 15 ,!XSI == 24)#, "CMX", "MH", "MHRF", "CVG", "CRF")))  #, "CMX", "MH", "MHRF", "CVG", "CRF")))
interSI<- climSI %>% dplyr::filter(!str_detect(BGC, (coast)))# %>% 
  #dplyr::filter(!XSI == 18, !XSI == 21,!XSI == 15 ,!XSI == 24,!XSI == 12)#, "CMX", "MH", "MHRF", "CVG", "CRF")))


clim_coast <- climDat %>% dplyr::filter(str_detect(BGC, (coast))) %>% dplyr::select(BGC, DD5, DD18, EXT) 
clim_inter <- climDat %>% dplyr::filter(!str_detect(BGC, (coast))) %>% dplyr::select(BGC, DD5, DD18, EXT) 

```


``` {r plot}
SImaxc <- SppMaxSI[SppMaxSI$cos_int == "c", ]
pc <- ggplot(coastSI, aes(x = DD5, y = XSI))+
  geom_point() +
  #geom_point(shape = 21, fill = "red", size = 1)+
  geom_jitter(width = 0) +
  scale_y_continuous(limit = c(0, 45))+
     scale_x_continuous(limit = c(0, 5000))+
    ggtitle(paste0(SppCurr, " SI50 by DD5 in Coastal BGCs"))+
  geom_text (aes(label= BGC), size = 2, hjust = -.1, position = position_dodge(width=1) )+
  #geom_abline(intercept = -11, slope = .042, color = "green")+
  #geom_abline(intercept = -1.86715, slope = .0263, color = "red")+
  geom_hline(yintercept= (SppMaxSI$MaxSI), linetype="dashed", color = "red")+
geom_smooth(method = "loess")
  #geom_smooth(method = "lm")

  #scale_y_continuous("DD5", breaks=seq(0,8000,500))+
  #theme_bw()
  #geom_text (aes(label= BGC), size = 1, hjust = -1, position = position_dodge(width=1) )#
#ggsave("./outputs/CMD_ranges of Expert aSMR of Zonal.pdf", plot = p, dpi = "print", device = "pdf", width = 15, height = 15, units = "cm")
#ggsave("./outputs/CMD_ranges.png", plot = p, dpi = "print", device = "png", width = 15, height = 15, units = "cm")
plot(pc)


interSI2 <- interSI %>% filter(DD5 <=750)
SImaxi <- SppMaxSI[SppMaxSI$cos_int == "i", ]
#interSI2 <- interSI %>% dplyr::filter(!str_detect (BGC, "PPxh1|BGxh2|BGxh1"))
pi <- ggplot(interSI, aes(x = DD5, y = XSI))+
  geom_point() +
  #geom_point(shape = 21, fill = "red", size = 1)+
  geom_jitter(width = 0) +
 # coord_flip()+
    ggtitle(paste0(SppCurr, " SI50 by DD5 in Interior BGCs"))+   xlab ("DD5")+
   scale_x_continuous(limit = c(0, 3000))+
  scale_y_continuous(limit = c(0, 45))+
  #geom_segment(aes(x=350, y=0, xend=1100, yend = 28))+
  #geom_abline(intercept = -11, slope = .042, color = "green")+
  #geom_abline(intercept = -1.86715, slope = .0263, color = "red")+
  geom_hline(yintercept = (SImaxi$MaxSI), linetype="dashed", color = "red")+
    geom_text (aes(label= BGC), size = 2, hjust = -.1, position = position_dodge(width=1) )+
geom_smooth(method = "loess")
#geom_smooth(method = "lm")

#+
  #theme_bw()
  #geom_text (aes(label= BGC), size = 4, hjust = -.1, position = position_dodge(width=1) )#
#ggsave("./outputs/CMD_ranges of Expert aSMR of Zonal.pdf", plot = p, dpi = "print", device = "pdf", width = 15, height = 15, units = "cm")
#ggsave("./outputs/CMD_ranges.png", plot = p, dpi = "print", device = "png", width = 15, height = 15, units = "cm")
plot(pi)

#interSI2 <- interSI %>% dplyr::filter(!str_detect (BGC, "PPxh1|BGxh2|BGxh1"))
pall <- ggplot(climSI, aes(x = DD5, y = XSI))+
  geom_point() +
  #geom_point(shape = 21, fill = "red", size = 1)+
  geom_jitter(width = 0) +
 # coord_flip()+
    ggtitle(paste0(SppCurr, " SI50 by DD5 in all BGCs"))+   xlab ("DD5")+
   scale_x_continuous(limit = c(0, 3000))+
  scale_y_continuous(limit = c(0, 45))+
  #geom_segment(aes(x=350, y=0, xend=1100, yend = 28))+
  #geom_abline(intercept = -11, slope = .042, color = "green")+
  #geom_abline(intercept = -1.86715, slope = .0263, color = "red")+
  geom_hline(yintercept = (SImaxi$MaxSI), linetype="dashed", color = "red")+
    geom_text (aes(label= BGC), size = 2, hjust = -.1, position = position_dodge(width=1) )+
geom_smooth(method = "loess")

plot(pall)

```

```{r build loess and extrapolate}
## interior
spp.lo <- loess(XSI ~ DD5, interSI, control = loess.control(surface = "direct"))
PredictedSI <- predict(spp.lo, newdata = clim_inter , se = F)
PredictedSI_int <- cbind(clim_inter, PredictedSI)
#write.csv(PredictedSI_int, paste0("./outputs/", Spp, "_interior_SIpotential_predicted.csv"))

## coast
spp.lo2 <- loess(XSI ~ DD5, coastSI, control = loess.control(surface = "direct"))
PredictedSI <- predict(spp.lo2, newdata = clim_coast , se = F)
PredictedSI_coast <- cbind(clim_coast, PredictedSI)
#write.csv(PredictedSI_coast, paste0("./outputs/", Spp, "_coast_SIpotential_predicted.csv"))
## all

spp.lo3 <- loess(XSI ~ DD5, climSI, control = loess.control(surface = "direct"))
PredictedSI <- predict(spp.lo3, newdata = climDat , se = F)
PredictedSI_all <- cbind(climDat, PredictedSI)


```

```{r plot predicted}
#pi <- 
  ggplot(PredictedSI_int, aes(x = DD5, y = PredictedSI))+
  geom_point() +
  #geom_point(shape = 21, fill = "red", size = 1)+
  geom_jitter(width = 0) +
  scale_y_continuous(limit = c(0, 45))+
     scale_x_continuous(limit = c(0, 5000))+
    ggtitle(paste0(SppCurr, " climatic maximum SI50 Predicted  by DD5 in interior BGCs"))+
  geom_text (aes(label= BGC), size = 2, hjust = -.1, position = position_dodge(width=1) )+
  #geom_abline(intercept = -11, slope = .042, color = "green")+
  #geom_abline(intercept = -1.86715, slope = .0263, color = "red")+
  geom_hline(yintercept= (SppMaxSI$MaxSI), linetype="dashed", color = "red")+
geom_smooth(method = "loess")

#ggsave(paste0 ("./outputs/", Spp, "_interior_SIpotential_predicted.jpg"))

#pc <- 
  ggplot(PredictedSI_coast, aes(x = DD5, y = PredictedSI))+
  geom_point() +
  #geom_point(shape = 21, fill = "red", size = 1)+
  geom_jitter(width = 0) +
  scale_y_continuous(limit = c(0, 45))+
     scale_x_continuous(limit = c(0, 5000))+
    ggtitle(paste0(SppCurr, " climatic maximum SI50 Predictedby DD5 in coastal BGCs"))+
  geom_text (aes(label= BGC), size = 2, hjust = -.1, position = position_dodge(width=1) )+
  #geom_abline(intercept = -11, slope = .042, color = "green")+
  #geom_abline(intercept = -1.86715, slope = .0263, color = "red")+
  geom_hline(yintercept= (SppMaxSI$MaxSI), linetype="dashed", color = "red")+
geom_smooth(method = "loess")
#ggsave(paste0 ("./outputs/", Spp, "_coast_SIpotential_predicted.jpg"))
  
  
    ggplot(PredictedSI_all, aes(x = DD5, y = PredictedSI))+
  geom_point() +
  #geom_point(shape = 21, fill = "red", size = 1)+
  geom_jitter(width = 0) +
  scale_y_continuous(limit = c(0, 45))+
     scale_x_continuous(limit = c(0, 5000))+
    ggtitle(paste0(SppCurr, " climatic maximum SI50 Predictedby DD5 in all BGCs"))+
  geom_text (aes(label= BGC), size = 2, hjust = -.1, position = position_dodge(width=1) )+
  #geom_abline(intercept = -11, slope = .042, color = "green")+
  #geom_abline(intercept = -1.86715, slope = .0263, color = "red")+
  geom_hline(yintercept= (SppMaxSI$MaxSI), linetype="dashed", color = "red")+
geom_smooth(method = "loess")

```

## Adjust by edatopic position

```{r eda_adjust}
predictComb <- as.data.table(rbind(PredictedSI_coast,PredictedSI_int))
predictComb <- predictComb[,.(BGC,PredictedSI)]
temp <- climDat[,.(BGC,CMD)]
predictComb <- temp[predictComb, on = "BGC"]

predictComb <- eda[predictComb, on = "BGC"]
predictComb[, CMDadj := calcCMD_vec(CMD,rSMR)]
predictComb[, aSMR := calcASMR(rSMR,CMDadj,rules)]
predictComb[, aSMR := round(aSMR, digits = 0)]

predictComb <- sppAdj[predictComb, on = c("aSMR","SNR")]
predictComb[,PredictedSI := PredictedSI*(as.numeric(value))]
predSIfinal <- predictComb[,.(BGC, SS_NoSpace, Edatopic, aSMR, PredictedSI)] ##each edatopic position
SIbySS <- predSIfinal[,.(SIPred = mean(PredictedSI), aSMRx = mean(aSMR)), by = .(SS_NoSpace)] ##averaged by site series

#write.csv(SIbySS, paste0("./outputs/", SppCurr, "_estimated_potential_SI.csv"))
```

```{r update table}
suit <- fread(paste0(cloud_dir,"Feasibility_v11_21.csv"))
suit <- suit[Spp  == SppCurr,.(BGC,SS_NoSpace,Spp,Feasible, Restrict_type)]
suit <- SIbySS[suit, on = "SS_NoSpace"]
temp <- sibec[,.(SS_NoSpace,SIBEC2013 = MeanPlotSiteIndex)]
suit <- temp[suit, on = "SS_NoSpace"]
suit <- suit[,.(BGC,SS_NoSpace,Spp,Feasible,SIBEC2013,SIPred, aSMRx)] %>% mutate(SIdiff = SIPred - SIBEC2013) %>% distinct()

write.csv(suit, paste0("./outputs/", SppCurr, "_estimated_potential_SI.csv"))
suit2 <- suit %>% dplyr::select(-aSMRx, -SIdiff)
library(RPostgreSQL)
dbSafeNames = function(names) {
  names = gsub('[^a-z0-9]+','_',tolower(names))
  names = make.names(names, unique=TRUE, allow_=TRUE)
  names = gsub('.','_',names, fixed=TRUE)
  names
}

colnames(suit2) <- dbSafeNames(colnames(suit2))
drv <- dbDriver("PostgreSQL")
# con <- dbConnect(drv, user = "postgres", password = "Kiriliny41", host = "smithersresearch.ca", 
#                  port = 5432, dbname = "common_tables")
# 
# ##if in Will's house, use this one
con <- dbConnect(drv, user = "postgres", password = "Kiriliny41", host = "FLNRServer",
                 port = 5432, dbname = "common_tables")

##Use dbGetQuery to return the result of a query as a data table
##Can also use dbReadTable(con, "si_working) to read entire table
##si_working <- dbGetQuery(con, "SELECT * FROM si_working WHERE sipred > 35")
##You can use dbExecute to updat a table, e.g.could use this to set the column sibec2013 to 0 where it's na
##dbExecute(con, "UPDATE si_working SET sibec2013 = 0 WHERE sibec2013 IS NULL")
##use this to append to a table
dbWriteTable(con, "si_working", suit, row.names = FALSE, append = TRUE)
###if you want to rewrite the table, do this
##dbWriteTable(con, "si_working", suit, row.names = FALSE, overwrite = TRUE)
##si_working <- dbGetQuery(con, "SELECT * FROM si_working")
dbWriteTable(con, "si_working", suit2, row.names = FALSE, append = TRUE)

dbDisconnect(con)

```


```{r climate space}

mahDist <- function(x, type){
  if(nrow(x) < 25 | any(colSums(x) == 0)){
    return(0)
  }else{
    t1 <- mahalanobis(x,center = colMeans(x), cov = cov(x),inverted = F)
    if(type == "mean"){
      return(mean(t1))
    }else{
      return(quantile(t1, 0.9))
    }
  }
 
}

climDat0 <- fread("C:/Users/whmacken/Sync/CCISS_data/CommonTables/WNA_4k_HexPts_BGC_Normal_1961_1990MSY.csv")

clim_test <- climDat0 %>% dplyr::select(BGC, PPT_sm, PPT_wt, CMD, Tmin_wt, DD5) %>% mutate (Tmin_wt = (Tmin_wt * 100))# dplyr::filter(ID2 == "IDFdk1") %>% droplevels()
test <- clim_test[!is.na(PPT_wt),. (Dist= mahDist(.SD,type = "quantile")),
                 by = .(BGC), .SDcols = c("CMD")] #,"PPT_sm","CMD", "DD5", "Tmin_wt""PPT_wt"

```




