---
title: "Prep SIBEC data for SiteTools"
author: "William H MacKenzie"
date: "29/11/2019"
output:
  pdf_document: default
  html_document: default
---
# Evaluation of SIBEC values
This script was built to look at the range of site index by site series or other site factors for the SIBEC dataset compiled by Atticus from the original data sets.

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
options(tinytex.verbose = TRUE)
require(tidyverse)
require(TeachingDemos)
require (ggplot2)
require (assertr)
require(data.table)
require(tinytex)
require(DBI)
library(purrr)
```

##Import Vtrees data

Read in SIBEC data from a .csv table export of a _Trees table from the VTrees database

```{r Vtrees data import}
sibec_master <- dbConnect(odbc::odbc(), .connection_string = "Driver={Microsoft Access Driver (*.mdb, *.accdb)}; DBQ=D:/OneDrive - Government of BC/SIBEC_files/SIBEC_2024_Prov_VPRO_Master.accdb;")
sibec  <- dbReadTable(sibec_master, "SIBEC_All_2024_ENV")
sibec.tree  <- dbReadTable(sibec_master, "SIBEC_All_2024_Trees")
sibec.info  <- dbReadTable(sibec_master, "SIBEC_All_2024_TreePlot")
#SI_raw  <- dbReadTable(sibec_master, "SIBEC_Analysis_Data")
dbDisconnect(sibec_master)

sibec.tree$TreeSpp <- sibec.tree$TreeSpp %>% recode(
  "Sw" = "Sx", "sw" = "Sx", "Se" = "Sx", "SX" = "Sx", "HW" = "Hw",
  "EP"= "Ep", "FD" = "Fd", "Fd " = "Fd", "PL" = "Pl")
SI_clean <-  sibec.tree %>% select(PlotNumber,TreeSpp, TreeNum, CountAge, TotalHtCalc) %>% dplyr::rename(Species = TreeSpp, `BHAge` = CountAge, `Height` = TotalHtCalc ) %>% mutate(PlotNumber= paste0("SI_",PlotNumber))
write.csv(SI_clean, "./for_sitetools/SIBEC_2024_ForSiteTools_v2.csv", row.names = FALSE)
```

